### ISSUE TITLE
automated welcome email to signups

### ISSUE THREAD

**Issue by echolabstech** [coderbunker/coderbunker.com#55]
### What changed and why?
When someone signs up on the website, we don't follow up with a thank you email or any email instructions for what to do next.

### Background context or notes?
[how to make a google app script](https://www.codementor.io/olatundegaruba/google-apps-script-automated-emails-m2m0ojq9v)

### todo (if appropriate):
- [ ] on a test account, create google app script to open signups spreadsheet
- [ ] read latest signup email address and name from spreadsheet
- [ ] draft an email response and send to email
- [ ] test and deploy script to coderbunker account

_____________________________________________________________________________________________________________________
### reviewer todo (if appropriate):
- [ ] at least one reviewer has seen this PR work on local
- [ ] this PR does not break tests

**Comment by Sunying-RONG** [comment]
- [ ] I created a form by Typeform and connected with spreadsheet to Dante's google drive, and moved it to CoderBunker Marketing drive, but I can't edit the spreadsheet there. We need to figure out how to edit the spreadsheet in Coderbunker's drive.
- [ ] I wrote these code for sending email automatically, we need to copy past these code in spreadsheet - tools - script editor and run it in Coderbunker's drive. The spread sheet should have the content (first row and tab name) in following pictures.
//
function sendNew(){
  var dataSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("data");
  var templetSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("template");
  var templateSubject = templetSheet.getRange(1, 2).getValue();
  var templateBody = templetSheet.getRange(2, 2).getValue();

  for (var i =2; i<= dataSheet.getLastRow(); i++){
    var name = dataSheet.getRange(i, 1).getValue();
    var emailAddress = dataSheet.getRange(i, 2).getValue();
    var status = dataSheet.getRange(i, 3).getValue();

    var subject = templateSubject.replace("<<Name>>", name);
    var body = templateBody.replace("<<Name>>", name);

    if (status == ""){
      MailApp.sendEmail(emailAddress, subject, body);
      dataSheet.getRange(i,3).setValue("Email Sent");
    } 
  }
}

ScriptApp.newTrigger("sendNew")
  .timeBased()
  .everyMinutes(1)
  .create();
//
![1555247304(1)](https://user-images.githubusercontent.com/44567186/56093348-3c6b2300-5efa-11e9-9f4f-5a9ca23906cd.png)
![1555247324(1)](https://user-images.githubusercontent.com/44567186/56093349-3f661380-5efa-11e9-89f6-b87cd6d4d8fd.png)

- [ ] After above steps, I need to update the <a href = ""> of join in button in HTML.

**Comment by Sunying-RONG** [comment]
We only need the following code to send email automatically.
For checking new entries, no need to use code, we can use the setting in Google script, as shown in following picture: 
//
function sendNew(){
var dataSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("data");
var templetSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("template");
var templateSubject = templetSheet.getRange(1, 2).getValue();
var templateBody = templetSheet.getRange(2, 2).getValue();

for (var i =2; i<= dataSheet.getLastRow(); i++){
var name = dataSheet.getRange(i, 1).getValue();
var emailAddress = dataSheet.getRange(i, 2).getValue();
var status = dataSheet.getRange(i, 3).getValue();

var subject = templateSubject.replace("<>", name);
var body = templateBody.replace("<>", name);

if (status == ""){
MailApp.sendEmail(emailAddress, subject, body);
dataSheet.getRange(i,3).setValue("Email Sent");
}
}
}
//
![image](https://user-images.githubusercontent.com/44567186/56465197-96ed0d80-642b-11e9-809a-a828ea20e350.png)

**Comment by rngadam** [comment]
This is redundant work to what @ancagabriela has done internally for the script to onboard people.

The full onboarding procedure is described here:

https://docs.google.com/document/d/1OskzP7OSv1wWe212Qgz_MpNTdNQcpgQbZAYKxjX12uA/edit#

We send out this PDF at the moment:

[Coderbunker email registration.pdf](https://github.com/coderbunker/coderbunker.com/files/3144069/Coderbunker.email.registration.pdf)

This creates an entry on Coderbunker Categorization:

https://docs.google.com/spreadsheets/d/11fWotgVODH5xuj6OH9YunbJCMnqCWD1Ud-pyJ_ID52A/edit#gid=0

Then we MANUALLY run a script

https://script.google.com/d/1Nnxm0mLzRMObgh_sO892JC05h5r_5eQTo3nXqDT_mbZoebpYLxTONPcB/edit

@Sunying-RONG read and integrate the script. I think what's interesting here is that you figured out a way to automatically run the mail sending script - that's the functionality we need to integrate to the next step.
